# HTCondor submit description file
# Everything with a leading # is a comment

universe                = vanilla

initialdir              = /nethome/fmeng
output                  = /scratch/fmeng/ActAdd/logs/run.sh.$(ClusterId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).out
error                   = /scratch/fmeng/ActAdd/logs/run.sh.$(ClusterId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).err
log                     = /scratch/fmeng/ActAdd/logs/run.sh.$(ClusterId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).log
request_CPUs            = 6
request_memory          = 50G
request_GPUs            = 1
requirements            = (GPUs_GlobalMemoryMb >= 43000)
+MaxWallTime            = 43200

queue
